name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Cache Node.js modules (optional)
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Install system dependencies for Playwright
      - name: Install system dependencies for Playwright
        run: |
          npx playwright install-deps

      # Step 6: Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 7: Start Xvfb (virtual display)
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          export DISPLAY=:99

      # Step 8: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        env:
          DISPLAY: :99